name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Debug APK with Stacktrace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ensure Gradle Wrapper JAR is present
        run: |
          mkdir -p gradle/wrapper
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Downloading gradle-wrapper.jar..."
            curl -L -o gradle-wrapper.zip https://services.gradle.org/distributions/gradle-8.0-bin.zip
            unzip -j gradle-wrapper.zip gradle/wrapper/gradle-wrapper.jar -d gradle/wrapper
          fi

      - name: Grant Permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Debug APK with Stacktrace
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnimeCharacter-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
