name: Build Android APK with Gradle Wrapper 8.4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Remove old Gradle Wrapper
        run: rm -rf gradle/wrapper

      - name: Create gradle/wrapper directory if missing
        run: mkdir -p gradle/wrapper

      - name: Generate Gradle Wrapper version 8.4
        run: ./gradlew wrapper --gradle-version 8.4

      - name: Build Debug APK with stacktrace
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnimeCharacter-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
