name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Clean gradle wrapper folder
        run: rm -rf gradle/wrapper

      - name: Create gradle wrapper folder
        run: mkdir -p gradle/wrapper

      - name: Download Gradle distribution zip
        run: curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.0-bin.zip

      - name: List contents of gradle.zip
        run: unzip -l gradle.zip

      - name: Extract gradle wrapper files
        run: |
          unzip -j gradle.zip gradle-8.0/gradle/wrapper/gradle-wrapper.jar gradle-8.0/gradle/wrapper/gradle-wrapper.properties -d gradle/wrapper || \
          unzip -j gradle.zip gradle-8.0/lib/gradle-wrapper.jar gradle-8.0/lib/gradle-wrapper.properties -d gradle/wrapper

      - name: Remove gradle.zip
        run: rm gradle.zip

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnimeCharacter-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
