name: Build Android APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Debug APK with Stacktrace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Debug APK with Stacktrace
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnimeCharacter-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
